//
//  RedditPostModel.swift
//  SignalMVP
//
//  Created by Krishna Venkatramani on 23/09/2022.
//

import Foundation

//MARK: - RedditPostResult

struct RedditPostResult: Codable {
	let data: [String : RedditPostModel]
}

// MARK: - RedditPost
struct RedditPostModel: Codable {
	let author: String
	let authorFullname: String
//	let edited: Edited?
	let id: String
//	let isSelf: Bool
	let name: String
//	let numComments: Double
//	let opinions: Opinions
//	let over18: Bool
	let permalink: String
	//let reactions: Reactions
	let saved: Bool
	let score: Double
	let selftext: String?
	let spoiler, stickied: Bool
	let subreddit, title: String
	let subredditNamePrefixed: String
//	let upvoteRatio: Double
	let url: String
		
	enum CodingKeys: String, CodingKey {
		case author
		case authorFullname = "author_fullname"
		case id
//		case isSelf = "is_self"
		case name, permalink, saved, score, selftext, spoiler, stickied, subreddit
		case subredditNamePrefixed = "subreddit_name_prefixed"
		case title, url
	}
}

enum Edited: Codable {
	case bool(Bool)
	case string(String)
}

// Auto-generated by Firefoo v1.4.1 on 2022-09-23 06:42:14 UTC

// MARK: - Opinions
struct Opinions: Codable {
	let bearish, bullish: Double
}

// Auto-generated by Firefoo v1.4.1 on 2022-09-23 06:42:14 UTC

// MARK: - Reactions
struct Reactions: Codable {
	let badAnalysis, fakeNews, overreaction, qualityAnalysis: Double
	let trustedNews: Double
}
